/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                status: string;
                                db: string;
                                openai: string;
                                auth: string;
                                version: string;
                                uptimeSec: number;
                            };
                            meta: {
                                requestId: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Code emailed (devCode only outside production with the console mail provider) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                sentTo: string;
                                /** Format: date-time */
                                expiresAt: string;
                                devCode?: string;
                            };
                            meta: {
                                requestId: string;
                            };
                        };
                    };
                };
                /** @description OTP_RATE_LIMITED */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        otpCode?: string;
                    };
                };
            };
            responses: {
                /** @description Session created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                sessionId: string;
                                /** Format: date-time */
                                expiresAt: string;
                                user: components["schemas"]["AuthUser"];
                                tenant: components["schemas"]["AuthTenant"];
                            };
                            meta: {
                                requestId: string;
                            };
                        };
                    };
                };
                /** @description UNAUTHENTICATED | OTP_REQUIRED | OTP_INVALID | OTP_EXPIRED */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description CONCURRENT_LOGIN_BLOCKED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                loggedOut: boolean;
                            };
                            meta: {
                                requestId: string;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                user: components["schemas"]["AuthUser"];
                                tenant: components["schemas"]["AuthTenant"];
                                sessionId: string;
                            };
                            meta: {
                                requestId: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    category?: "auth" | "session" | "config" | "dataset" | "assessment" | "decision" | "retention" | "access";
                    entityType?: string;
                    entityId?: string;
                    from?: string | null;
                    to?: string | null;
                    limit?: number;
                    cursorSeq?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit entries (newest first) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                items: {
                                    [key: string]: unknown;
                                }[];
                                nextCursorSeq: number | null;
                            };
                            meta: {
                                requestId: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hash chain verification */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                ok: boolean;
                                checked: number;
                                firstBadSeq?: number;
                            };
                            meta: {
                                requestId: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
            meta: {
                requestId: string;
            };
        };
        AuthUser: {
            id: string;
            firebaseUid: string;
            /** Format: email */
            email: string;
            name: string;
            /** @enum {string} */
            role: "requestor" | "administrator" | "system_administrator" | "audit";
            tenantId: string;
            departmentIds: string[];
            crossDepartmentAccess: boolean;
            mfaEnrolled: boolean;
        };
        AuthTenant: {
            id: string;
            slug: string;
            /** @enum {string} */
            plan: "free" | "paid";
            features: {
                sso: boolean;
                reviewDashboard: boolean;
                reports: boolean;
                fullAudit: boolean;
                departmentMapping: boolean;
                blockConcurrentLogin: boolean;
            };
            sessionPolicy: {
                idleTimeoutMin: number;
                maxConcurrentSessions: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
